#define PWM_MOTOR_DIREITA 5
#define PWM_MOTOR_ESQUERDA 8

//// ENABLE MOTORES ////
#define ENABLE_MOTOR_DIREITA A0
#define ENABLE_MOTOR_ESQUERDA A1

//// PINOS DIREÇÕES MOTOR DIREITA //// 
#define DIRECAO_HORARIO_DIREITA 6
#define DIRECAO_ANTIHORARIO_DIREITA 7

//// PINOS DEIREÇÕES MOTOR ESQUERDA ////
#define DIRECAO_HORAIO_ESQUERDA 12
#define DIRECAO_ANTIHORARIO_ESQUERDA 11

void setup() 
{

  pinMode(PWM_MOTOR_DIREITA, OUTPUT);
  pinMode(PWM_MOTOR_ESQUERDA, OUTPUT);

  pinMode(ENABLE_MOTOR_DIREITA, OUTPUT);
  pinMode(ENABLE_MOTOR_ESQUERDA, OUTPUT);

  pinMode(DIRECAO_HORARIO_DIREITA, OUTPUT);
  pinMode(DIRECAO_ANTIHORARIO_DIREITA, OUTPUT);

  pinMode(DIRECAO_HORAIO_ESQUERDA, OUTPUT);
  pinMode(DIRECAO_ANTIHORARIO_ESQUERDA, OUTPUT);

  Serial.begin(9600);
}

void loop() {

  //// PARTE DO CODIGO ESCRITO PELA GABRIELA ////
//=====TESTE-PARA-FUNCIONAMENTO-DOS-MOTORES=====//
//=====MOTOR-SE-MOVE-PARA-FRENTE=====//
  digitalWrite(ENABLE_MOTOR_DIREITA, HIGH);
  digitalWrite(ENABLE_MOTOR_ESQUERDA, HIGH);

  digitalWrite(DIRECAO_HORARIO_DIREITA, HIGH);
  digitalWrite(DIRECAO_ANTIHORARIO_DIREITA, LOW);
  analogWrite(PWM_MOTOR_DIREITA, 255);

  digitalWrite(DIRECAO_HORAIO_ESQUERDA, LOW);
  digitalWrite(DIRECAO_ANTIHORARIO_ESQUERDA, HIGH);
  analogWrite(PWM_MOTOR_ESQUERDA, 255);

  delay(5000); 

//=====MOTOR-SE-MOVE-PARA-TRAS=====//
  digitalWrite(ENABLE_MOTOR_DIREITA, HIGH);
  digitalWrite(ENABLE_MOTOR_ESQUERDA, HIGH);

  digitalWrite(DIRECAO_HORARIO_DIREITA, LOW);
  digitalWrite(DIRECAO_ANTIHORARIO_DIREITA, HIGH);
  analogWrite(PWM_MOTOR_DIREITA, 255);

  digitalWrite(DIRECAO_HORAIO_ESQUERDA, HIGH);
  digitalWrite(DIRECAO_ANTIHORARIO_ESQUERDA, LOW);
  analogWrite(PWM_MOTOR_ESQUERDA, 255);

  delay(5000);

  //// PARTE DO CODIGO ESCRITO PELA GABRIELA ////
  
}
